## Loading data with Pandas

In [1]:
import pandas as pd

In [6]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data' #Data URL
df_data = pd.read_csv(data_url, sep='\s+', header = None) #csv 타입 데이터 로드, separate는 빈공간으로 지정하고, Column은 없음

#\s+ 블랭크가 여러개 있으면, 그거를 separation으로 보라는 뜻.

In [7]:
df_data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [8]:
df_data.columns = ['CRIM','ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO' ,'B', 'LSTAT', 'MEDV'] 
# Column Header 이름 지정
df_data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

## Representing a model with numpy<br>
y = b1w1+b2w2+...... 이런것들을 표현하고 싶다.<br>
벡터를 Array로 표현하기. <br>
<br>

***numpy***를 사용할 것

In [9]:
import numpy as np

In [10]:
weight_vector = np.array([[1], [1], [1]])
x_vector = np.array([[3], [4], [5]])

In [12]:
weight_vector

array([[1],
       [1],
       [1]])

In [13]:
x_vector

array([[3],
       [4],
       [5]])

In [11]:
weight_vector.T.dot(x_vector)

array([[12]])

In [14]:
import pandas as pd

In [16]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data' #Data URL
df_data = pd.read_csv(data_url, sep='\s+', header = None) #csv 타입 데이터 로드, separate는 빈공간으로 지정하고, Column은 없음
df_data.columns = ['CRIM','ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO' ,'B', 'LSTAT', 'MEDV'] 
df_data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [17]:
df_data['weight_0'] = 1 # weight 0 값 추가
df_data= df_data.drop("MEDV", axis=1) #Y값 제거
df_data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,weight_0
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,1
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,1
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,1
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,1
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,1

In [24]:
df_data.as_matrix() #large_X

array([[  6.32000000e-03,   1.80000000e+01,   2.31000000e+00, ...,
          3.96900000e+02,   4.98000000e+00,   1.00000000e+00],
       [  2.73100000e-02,   0.00000000e+00,   7.07000000e+00, ...,
          3.96900000e+02,   9.14000000e+00,   1.00000000e+00],
       [  2.72900000e-02,   0.00000000e+00,   7.07000000e+00, ...,
          3.92830000e+02,   4.03000000e+00,   1.00000000e+00],
       ...,
       [  6.07600000e-02,   0.00000000e+00,   1.19300000e+01, ...,
          3.96900000e+02,   5.64000000e+00,   1.00000000e+00],
       [  1.09590000e-01,   0.00000000e+00,   1.19300000e+01, ...,
          3.93450000e+02,   6.48000000e+00,   1.00000000e+00],
       [  4.74100000e-02,   0.00000000e+00,   1.19300000e+01, ...,
          3.96900000e+02,   7.88000000e+00,   1.00000000e+00]])

In [26]:
df_matrix= df_data.as_matrix()
weight_vector = np.random.random_sample((14, 1))

In [29]:
weight_vector.shape

(14, 1)

In [28]:
df_matrix.shape

(506, 14)

In [30]:
df_matrix.dot(weight_vector)

array([[ 451.70820793],
       [ 431.26093725],
       [ 423.06135967],
       [ 411.27802117],
       [ 415.8557734 ],
       [ 413.66816596],
       [ 465.6322398 ],
       [ 475.29445648],
       [ 473.48420281],
       [ 464.60309683],
       [ 472.63027631],
       [ 469.88341365],
       [ 459.05393918],
       [ 453.20120989],
       [ 444.55707571],
       [ 451.32219696],
       [ 439.38492331],
       [ 451.82345085],
       [ 365.41120388],
       [ 450.94161605],
       [ 449.57814274],
       [ 456.99378207],
       [ 463.87481936],
       [ 463.61436619],
       [ 460.62019367],
       [ 387.46240765],
       [ 445.38929208],
       [ 391.13530251],
       [ 454.15831238],
       [ 446.68220069],
       [ 437.12561152],
       [ 446.08851713],
       [ 337.66293437],
       [ 433.61079712],
       [ 348.34313247],
       [ 443.47254119],
       [ 428.07336669],
       [ 438.96349962],
       [ 435.35187796],
       [ 472.76288526],
       [ 470.87282404],
       [ 406.40425209],
       [ 405.41084035],
       [ 415.11089286],
       [ 417.34026265],
       [ 422.16629673],
       [ 424.40567714],
       [ 432.22951076],
       [ 443.33845338],
       [ 430.18494369],
       [ 443.4689516 ],
       [ 442.72987579],
       [ 436.56705516],
       [ 437.9553702 ],
       [ 558.03738739],
       [ 477.08244657],
       [ 502.17016229],
       [ 493.55998926],
       [ 454.30034513],
       [ 462.82082245],
       [ 466.51961107],
       [ 458.06907216],
       [ 465.14717194],
       [ 462.41663141],
       [ 425.94036977],
       [ 506.73824758],
       [ 511.51294252],
       [ 465.92068594],
       [ 471.44971608],
       [ 468.68023442],
       [ 435.39878429],
       [ 433.1482336 ],
       [ 440.27892316],
       [ 430.51845113],
       [ 477.89510788],
       [ 476.01316043],
       [ 474.57092274],
       [ 479.56604797],
       [ 481.88822582],
       [ 484.58047816],
       [ 453.31348253],
       [ 459.01061269],
       [ 453.55853499],
       [ 451.18865139],
       [ 426.87846706],
       [ 422.84743323],
       [ 427.10577975],
       [ 425.62615752],
       [ 436.18223949],
       [ 432.10466531],
       [ 430.58985173],
       [ 432.51909955],
       [ 464.07752131],
       [ 460.00334405],
       [ 470.42169875],
       [ 402.92849085],
       [ 433.72272868],
       [ 436.30364145],
       [ 427.01628115],
       [ 434.76275099],
       [ 482.03981592],
       [ 480.42980496],
       [ 227.59855983],
       [ 484.74234082],
       [ 483.01115819],
       [ 487.07952858],
       [ 488.8893697 ],
       [ 479.17804062],
       [ 486.34566982],
       [ 484.00316213],
       [ 478.65161665],
       [ 501.49837693],
       [ 505.37390048],
       [ 508.05117925],
       [ 496.14224049],
       [ 464.96431068],
       [ 498.91993851],
       [ 500.33667751],
       [ 457.39596602],
       [ 496.89606572],
       [ 425.63263377],
       [ 418.83334511],
       [ 422.52359328],
       [ 421.12075814],
       [ 423.69829827],
       [ 425.55822743],
       [ 413.07470022],
       [ 515.6977492 ],
       [ 519.5533994 ],
       [ 520.18874865],
       [ 516.65861388],
       [ 518.02561047],
       [ 508.44058082],
       [ 512.05329801],
       [ 414.56035809],
       [ 518.69677662],
       [ 504.50313308],
       [ 516.85705446],
       [ 518.40621399],
       [ 520.94740867],
       [ 516.43630488],
       [ 529.66201583],
       [ 513.66455487],
       [ 513.19690269],
       [ 513.4571451 ],
       [ 337.05703341],
       [ 327.4158594 ],
       [ 509.0674532 ],
       [ 480.91370456],
       [ 473.65635978],
       [ 486.46794182],
       [ 461.11719325],
       [ 460.09790917],
       [ 399.95626721],
       [ 446.5584591 ],
       [ 261.3637829 ],
       [ 262.43783106],
       [ 474.09845297],
       [ 467.27386509],
       [ 476.68529344],
       [ 454.56487451],
       [ 480.73537783],
       [ 495.03485074],
       [ 494.64501288],
       [ 501.88075962],
       [ 379.15768645],
       [ 479.24369635],
       [ 367.84954382],
       [ 425.17742513],
       [ 451.3544424 ],
       [ 422.33893901],
       [ 465.90658861],
       [ 452.43462048],
       [ 448.1740063 ],
       [ 443.88693345],
       [ 434.88204556],
       [ 441.24754245],
       [ 445.17450911],
       [ 442.5961966 ],
       [ 405.54612596],
       [ 410.39299262],
       [ 407.84124173],
       [ 408.56731658],
       [ 411.32495406],
       [ 409.68398892],
       [ 403.45371256],
       [ 401.94364238],
       [ 505.11942689],
       [ 493.45288656],
       [ 507.04753801],
       [ 489.47336664],
       [ 499.98710187],
       [ 499.25863682],
       [ 461.33429691],
       [ 449.01611722],
       [ 476.25394525],
       [ 503.1073338 ],
       [ 472.28144348],
       [ 501.46697119],
       [ 537.03042497],
       [ 526.93619311],
       [ 510.82817312],
       [ 507.37304198],
       [ 478.04851691],
       [ 475.70984965],
       [ 440.04547174],
       [ 443.70703564],
       [ 446.08294162],
       [ 436.44856864],
       [ 459.20750287],
       [ 452.24129965],
       [ 456.59433568],
       [ 443.61358044],
       [ 432.4066408 ],
       [ 410.32105359],
       [ 440.05009022],
       [ 447.48302469],
       [ 449.92551846],
       [ 459.05034866],
       [ 452.6720225 ],
       [ 456.3429135 ],
       [ 465.61443128],
       [ 453.946279  ],
       [ 457.39253977],
       [ 446.8450393 ],
       [ 445.91099849],
       [ 449.32498196],
       [ 437.32171029],
       [ 430.96404342],
       [ 432.8865485 ],
       [ 442.63575226],
       [ 439.82032835],
       [ 446.29203945],
       [ 440.95016154],
       [ 427.25501261],
       [ 439.92217625],
       [ 452.05421325],
       [ 449.84018303],
       [ 449.55615934],
       [ 457.34622524],
       [ 467.67659587],
       [ 471.90051314],
       [ 452.54346147],
       [ 443.76119   ],
       [ 463.00523277],
       [ 478.53212546],
       [ 469.17912153],
       [ 465.54256731],
       [ 459.49326968],
       [ 468.21377888],
       [ 468.79176258],
       [ 451.68015178],
       [ 459.33567187],
       [ 469.3334733 ],
       [ 497.52058208],
       [ 498.64578317],
       [ 476.15044367],
       [ 446.75286602],
       [ 444.11743115],
       [ 450.05708921],
       [ 449.74210229],
       [ 446.38001535],
       [ 445.53696525],
       [ 453.33569592],
       [ 446.48543585],
       [ 445.63387294],
       [ 446.16082121],
       [ 440.70230969],
       [ 440.04854271],
       [ 435.43445864],
       [ 429.51425531],
       [ 428.69524306],
       [ 434.41835607],
       [ 431.1964646 ],
       [ 455.41912704],
       [ 456.16563168],
       [ 453.97679053],
       [ 452.55580454],
       [ 456.52375498],
       [ 426.13588449],
       [ 423.92363991],
       [ 423.52366634],
       [ 413.8008505 ],
       [ 462.64908542],
       [ 494.37396276],
       [ 475.16601805],
       [ 434.08079976],
       [ 479.94598524],
       [ 482.50703673],
       [ 460.41177277],
       [ 478.52771727],
       [ 478.88613106],
       [ 478.41057423],
       [ 445.78713497],
       [ 450.40615862],
       [ 447.08392525],
       [ 447.45455272],
       [ 456.01310017],
       [ 484.76107675],
       [ 486.2913898 ],
       [ 507.88990545],
       [ 482.11005137],
       [ 468.60292176],
       [ 472.14326087],
       [ 438.98345199],
       [ 441.7424012 ],
       [ 445.87696719],
       [ 445.76346165],
       [ 454.76038646],
       [ 455.71718471],
       [ 414.93116781],
       [ 450.44038796],
       [ 458.78631626],
       [ 453.51313413],
       [ 457.20979272],
       [ 456.8968041 ],
       [ 457.30363298],
       [ 458.94373454],
       [ 454.1679386 ],
       [ 454.97165845],
       [ 444.59808776],
       [ 444.68425873],
       [ 444.31735077],
       [ 445.50349015],
       [ 442.22399063],
       [ 435.35995812],
       [ 440.6424339 ],
       [ 446.45594269],
       [ 473.05243338],
       [ 464.92661802],
       [ 463.04333561],
       [ 466.67843965],
       [ 438.48732512],
       [ 413.1379747 ],
       [ 413.54818864],
       [ 419.17211039],
       [ 421.60712251],
       [ 422.59038071],
       [ 418.9082815 ],
       [ 421.39945817],
       [ 423.15777362],
       [ 456.62949328],
       [ 477.35506127],
       [ 509.09516111],
       [ 496.62363073],
       [ 454.58682611],
       [ 439.69529218],
       [ 515.80756701],
       [ 485.12459568],
       [ 472.00413254],
       [ 478.783147  ],
       [ 500.29402973],
       [ 515.32352708],
       [ 458.32756408],
       [ 497.25952978],
       [ 490.40970261],
       [ 602.34579052],
       [ 607.91780713],
       [ 609.34223463],
       [ 604.89855315],
       [ 590.76511533],
       [ 575.5037964 ],
       [ 596.94855746],
       [ 577.59520308],
       [ 574.74399659],
       [ 571.95558134],
       [ 546.74510552],
       [ 404.76301286],
       [ 589.23513091],
       [ 591.24771941],
       [ 604.69089821],
       [ 588.08063263],
       [ 571.67058434],
       [ 626.25553653],
       [ 630.31212724],
       [ 619.33432583],
       [ 595.15412991],
       [ 619.59146512],
       [ 625.68035509],
       [ 620.28463798],
       [ 647.6164187 ],
       [ 621.77646391],
       [ 619.89531334],
       [ 619.9365169 ],
       [ 538.09133959],
       [ 626.40285231],
       [ 627.74399068],
       [ 627.81709778],
       [ 606.40410386],
       [ 617.69273741],
       [ 613.21076819],
       [ 598.9410685 ],
       [ 621.18889325],
       [ 614.40324986],
       [ 616.990177  ],
       [ 612.81846348],
       [ 616.34499866],
       [ 614.24306741],
       [ 635.22586986],
       [ 574.21407447],
       [ 628.31130782],
       [ 620.70854204],
       [ 602.53701892],
       [ 623.14870065],
       [ 579.28509443],
       [ 633.34407455],
       [ 601.88157138],
       [ 563.28441946],
       [ 555.45194945],
       [ 449.08083439],
       [ 317.6265274 ],
       [ 335.68797251],
       [ 338.33531924],
       [ 478.41338898],
       [ 397.40087428],
       [ 335.52467373],
       [ 325.21231437],
       [ 413.58079299],
       [ 343.68677492],
       [ 342.94692888],
       [ 554.96729866],
       [ 553.6567969 ],
       [ 530.73650509],
       [ 305.83091794],
       [ 301.24514497],
       [ 315.43282022],
       [ 316.8773126 ],
       [ 324.91480921],
       [ 378.34336198],
       [ 355.01303166],
       [ 367.43842948],
       [ 369.2283926 ],
       [ 373.28137623],
       [ 379.25843996],
       [ 383.17059769],
       [ 394.21625143],
       [ 327.16413999],
       [ 318.60217701],
       [ 367.26453481],
       [ 618.81887199],
       [ 619.01873937],
       [ 609.67093732],
       [ 614.35370286],
       [ 610.4664989 ],
       [ 497.87625315],
       [ 341.54600838],
       [ 553.52966903],
       [ 609.85474162],
       [ 617.45393262],
       [ 544.35394404],
       [ 302.5569749 ],
       [ 583.20289514],
       [ 605.04055199],
       [ 600.82114768],
       [ 309.66740552],
       [ 341.01788012],
       [ 309.3621638 ],
       [ 302.93601547],
       [ 515.29495492],
       [ 612.37929957],
       [ 502.08907312],
       [ 607.62491365],
       [ 611.90986469],
       [ 608.31741607],
       [ 609.1578768 ],
       [ 555.49240716],
       [ 316.59376379],
       [ 564.70826939],
       [ 593.29021661],
       [ 610.21393889],
       [ 612.30901846],
       [ 610.0857895 ],
       [ 606.9181562 ],
       [ 590.2906732 ],
       [ 580.76731467],
       [ 545.00318746],
       [ 614.85429186],
       [ 584.99037588],
       [ 603.75020394],
       [ 604.06826589],
       [ 606.93086741],
       [ 604.14373602],
       [ 606.09905174],
       [ 598.4759569 ],
       [ 582.69260841],
       [ 597.77489382],
       [ 608.24989521],
       [ 597.98275085],
       [ 615.52617435],
       [ 579.3940875 ],
       [ 562.10655057],
       [ 612.98808958],
       [ 613.40532919],
       [ 484.49482797],
       [ 483.85147807],
       [ 481.01599837],
       [ 492.48246761],
       [ 488.52097728],
       [ 487.05243696],
       [ 488.24967835],
       [ 490.10331344],
       [ 440.18851401],
       [ 444.43507549],
       [ 445.39268463],
       [ 442.82064469],
       [ 444.38971307]])